services:
  api:
    build: .
    ports: ["8000:8000"]
    environment:
      - BALLDONTLIE_API_KEY=${BALLDONTLIE_API_KEY:?Missing API key. Set this in your environment}
    volumes:
      - ./data:/app/data
